### ISSUE TITLE
use Github Flavoured Markdown to change README.md into a table

### ISSUE THREAD

**Issue by stemount** [qwe123coder/Spaceflight2d#11]
This would read nicer!

|Key|Action|
| --- | --- |
|**LEFT**|Turn left|
|**RIGHT**|Turn right|
|**UP**|Speed up|
|**RSHIFT**|Boost speed|
|**SPACE**|Shoot|
|**ESC**|Back/exit|
|**B**|Build a base (if landed on a planet without a base)|
|**F**|Oil refill (if landed on a base)|
|**R**|Repair (if landed on a base)|
|**D**|Drop some oil (if landed on a base)|
|**A**|Zoom in|
|**Z**|Zoom out|
|**M**|Open/close map|
|**E**|Hold down for ExtendedVision|
|**P**|Pause|
|**S**|Save game|

**Comment by qwe123coder** [comment]
cool I will do it

**Comment by qwe123coder** [comment]
done fixed thanks :)
