### ISSUE TITLE
Modularization

### ISSUE THREAD

**Issue by AbhijithGanesh** [qwe123coder/Spaceflight2d#9]
There is a bulk accumulation of code in main.py which can be modularized by adding them to different corresponding files, Please restructure accordingly.

**Comment by qwe123coder** [comment]
@AbhijithGanesh can you do pls

**Comment by AbhijithGanesh** [comment]
Please create a branch under the name of modularization which would be easier for us to coordinate.

**Comment by AbhijithGanesh** [comment]
I believe @qwe123coder asked me to work on this? I shall try my best and send in a patch here 😃

**Comment by qwe123coder** [comment]
> I believe @qwe123coder asked me to work on this? I shall try my best and send in a patch here

do you want to work on it or should I put it up in the #good first issue page ?

**Comment by AbhijithGanesh** [comment]
Can this be listed under help wanted too?

Also points to be kept in mind before modularized.

![image](https://user-images.githubusercontent.com/67182544/134107988-5b77a4a6-9af5-4369-9f7c-3f4341a3c9a5.png)

- So here if you see resume and new game are relatively better w.r.t other options and menus
- The modularity should attend to each feature in the game instead of random clustering
- When restructuring, please avoid using names like main, app, json, dump, binary, and other reserved names. They might be a good reason to run into circular dependency error if we don't categorize them well.

**Comment by AbhijithGanesh** [comment]
Closing this as files have been modularized.
